version: '2'
services:
  webapp:
    build: .
    ports:
     - "5000:5000"
    depends_on:
     - redis
  redis:
    image: redis
    command: redis-server --appendonly yes
    volumes:
     - ./redis_data:/data
